

/**
 * Découpage des quartiers, côté serveur.
 *
 * ⚠️ Ce fichier doit rester identique à `mobile/src/data/neighborhoods.ts`.
 * L'application en a besoin hors ligne (choix du quartier à l'inscription et
 * vérification de la position), le serveur en a besoin pour savoir quels fils
 * sont partagés. À regrouper dans un paquet commun quand il y en aura un
 * troisième usage.
 */

export interface Neighborhood {
  id: string;
  name: string;
  nameAr: string;
  wilaya: string;
  wilayaAr: string;
  wilayaCode: string;
  latitude: number;
  longitude: number;
  radiusMeters: number;
  verifiedNeighbors: number;
  twinnedWith?: string;
}

/**
 * Seuil de voisins vérifiés en dessous duquel un quartier reste jumelé avec un
 * quartier voisin, le temps d'avoir un fil vivant (§2 du cahier des charges).
 */
export const TWINNING_THRESHOLD = 50;

/**
 * Extrait du découpage administratif algérien réel (communes et wilayas), à
 * remplacer par le jeu de données complet partagé avec As3ar (§7.2) — d'où le
 * code de wilaya officiel porté par chaque entrée, qui sert de clé commune
 * entre les deux applications.
 *
 * Le regroupement se fait par quartier nommé, jamais par découpage géométrique
 * abstrait (§2) : les coordonnées ne servent qu'à vérifier qu'un nouveau voisin
 * habite bien là où il le déclare.
 *
 * Trois échelles cohabitent, faute d'un découpage fin partout :
 *  — les quartiers d'Alger, rayon de 2 à 3 km ;
 *  — les communes de Béjaïa, rayon de 4 à 6 km ;
 *  — le chef-lieu de chaque autre wilaya, rayon de 8 km, qui couvre la ville
 *    entière. Un chef-lieu se découpera en quartiers dès qu'il aura assez de
 *    voisins pour que ça ait un sens.
 * Personne ne doit rester sans entrée : un voisin qui ne se trouve pas dans la
 * liste ne peut pas s'inscrire.
 */
export const NEIGHBORHOODS: Neighborhood[] = [
  {
    id: 'bab-ezzouar',
    name: 'Bab Ezzouar',
    nameAr: 'باب الزوار',
    wilaya: 'Alger',
    wilayaAr: 'الجزائر',
    wilayaCode: '16',
    latitude: 36.7213,
    longitude: 3.1836,
    radiusMeters: 2500,
    verifiedNeighbors: 214,
  },
  {
    id: 'dar-el-beida',
    name: 'Dar El Beïda',
    nameAr: 'الدار البيضاء',
    wilaya: 'Alger',
    wilayaAr: 'الجزائر',
    wilayaCode: '16',
    latitude: 36.7133,
    longitude: 3.2122,
    radiusMeters: 2500,
    verifiedNeighbors: 96,
  },
  {
    id: 'bordj-el-kiffan',
    name: 'Bordj El Kiffan',
    nameAr: 'برج الكيفان',
    wilaya: 'Alger',
    wilayaAr: 'الجزائر',
    wilayaCode: '16',
    latitude: 36.7503,
    longitude: 3.1931,
    radiusMeters: 3000,
    verifiedNeighbors: 128,
  },
  {
    id: 'el-harrach',
    name: 'El Harrach',
    nameAr: 'الحراش',
    wilaya: 'Alger',
    wilayaAr: 'الجزائر',
    wilayaCode: '16',
    latitude: 36.7167,
    longitude: 3.1333,
    radiusMeters: 2500,
    verifiedNeighbors: 74,
  },
  {
    id: 'rouiba',
    name: 'Rouiba',
    nameAr: 'الرويبة',
    wilaya: 'Alger',
    wilayaAr: 'الجزائر',
    wilayaCode: '16',
    latitude: 36.7386,
    longitude: 3.2836,
    radiusMeters: 3000,
    verifiedNeighbors: 38,
    twinnedWith: 'dar-el-beida',
  },
  {
    id: 'reghaia',
    name: 'Reghaïa',
    nameAr: 'رغاية',
    wilaya: 'Alger',
    wilayaAr: 'الجزائر',
    wilayaCode: '16',
    latitude: 36.7353,
    longitude: 3.3403,
    radiusMeters: 3000,
    verifiedNeighbors: 22,
    twinnedWith: 'dar-el-beida',
  },
  {
    id: 'alger-centre',
    name: 'Alger-Centre',
    nameAr: 'الجزائر الوسطى',
    wilaya: 'Alger',
    wilayaAr: 'الجزائر',
    wilayaCode: '16',
    latitude: 36.7538,
    longitude: 3.0588,
    radiusMeters: 2000,
    verifiedNeighbors: 302,
  },
  {
    id: 'kouba',
    name: 'Kouba',
    nameAr: 'القبة',
    wilaya: 'Alger',
    wilayaAr: 'الجزائر',
    wilayaCode: '16',
    latitude: 36.7264,
    longitude: 3.0894,
    radiusMeters: 2500,
    verifiedNeighbors: 143,
  },
  {
    id: 'boumerdes-centre',
    name: 'Boumerdès Centre',
    nameAr: 'بومرداس الوسط',
    wilaya: 'Boumerdès',
    wilayaAr: 'بومرداس',
    wilayaCode: '35',
    latitude: 36.7594,
    longitude: 3.4722,
    radiusMeters: 3000,
    verifiedNeighbors: 61,
  },
  {
    id: 'blida-centre',
    name: 'Blida Centre',
    nameAr: 'البليدة الوسط',
    wilaya: 'Blida',
    wilayaAr: 'البليدة',
    wilayaCode: '09',
    latitude: 36.4703,
    longitude: 2.8277,
    radiusMeters: 3000,
    verifiedNeighbors: 88,
  },
  {
    id: 'bejaia-centre',
    name: 'Béjaïa Centre',
    nameAr: 'بجاية الوسط',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.7509,
    longitude: 5.0567,
    radiusMeters: 6000,
    verifiedNeighbors: 0,
  },
  {
    id: 'oued-ghir',
    name: 'Oued Ghir',
    nameAr: 'وادي غير',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.7083,
    longitude: 4.9583,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
    twinnedWith: 'bejaia-centre',
  },
  {
    id: 'toudja',
    name: 'Toudja',
    nameAr: 'توجة',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.7333,
    longitude: 4.9,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
    twinnedWith: 'bejaia-centre',
  },
  {
    id: 'tichy',
    name: 'Tichy',
    nameAr: 'تيشي',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.6656,
    longitude: 5.155,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
    twinnedWith: 'bejaia-centre',
  },
  {
    id: 'boukhelifa',
    name: 'Boukhelifa',
    nameAr: 'بوخليفة',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.6764,
    longitude: 5.1181,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
    twinnedWith: 'bejaia-centre',
  },
  {
    id: 'aokas',
    name: 'Aokas',
    nameAr: 'أوقاس',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.6392,
    longitude: 5.2528,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'souk-el-tenine',
    name: 'Souk El Ténine',
    nameAr: 'سوق الإثنين',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.5919,
    longitude: 5.3172,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'melbou',
    name: 'Melbou',
    nameAr: 'ملبو',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.6272,
    longitude: 5.3792,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'darguina',
    name: 'Darguina',
    nameAr: 'درقينة',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.5539,
    longitude: 5.2803,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'kherrata',
    name: 'Kherrata',
    nameAr: 'خراطة',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.4692,
    longitude: 5.2708,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'el-kseur',
    name: 'El Kseur',
    nameAr: 'القصر',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.6828,
    longitude: 4.8433,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'amizour',
    name: 'Amizour',
    nameAr: 'أميزور',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.6408,
    longitude: 4.9022,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'barbacha',
    name: 'Barbacha',
    nameAr: 'برباشة',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.5911,
    longitude: 4.9711,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'timezrit',
    name: 'Timezrit',
    nameAr: 'تيمزريت',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.6297,
    longitude: 4.7625,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'adekar',
    name: 'Adekar',
    nameAr: 'أدكار',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.7031,
    longitude: 4.7003,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'sidi-aich',
    name: 'Sidi Aïch',
    nameAr: 'سيدي عيش',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.6108,
    longitude: 4.6869,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'chemini',
    name: 'Chemini',
    nameAr: 'شميني',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.5822,
    longitude: 4.6161,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
    twinnedWith: 'sidi-aich',
  },
  {
    id: 'seddouk',
    name: 'Seddouk',
    nameAr: 'صدوق',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.5478,
    longitude: 4.6919,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
  },
  {
    id: 'akbou',
    name: 'Akbou',
    nameAr: 'أقبو',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.4581,
    longitude: 4.5383,
    radiusMeters: 5000,
    verifiedNeighbors: 0,
  },
  {
    id: 'ouzellaguen',
    name: 'Ouzellaguen',
    nameAr: 'أوزلاڨن',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.5253,
    longitude: 4.5836,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
    twinnedWith: 'akbou',
  },
  {
    id: 'tazmalt',
    name: 'Tazmalt',
    nameAr: 'تازمالت',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.3878,
    longitude: 4.3919,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
    twinnedWith: 'akbou',
  },
  {
    id: 'beni-maouche',
    name: 'Beni Maouche',
    nameAr: 'بني معوش',
    wilaya: 'Béjaïa',
    wilayaAr: 'بجاية',
    wilayaCode: '06',
    latitude: 36.4694,
    longitude: 4.7936,
    radiusMeters: 4000,
    verifiedNeighbors: 0,
    twinnedWith: 'akbou',
  },
  {
    id: 'adrar',
    name: 'Adrar',
    nameAr: 'أدرار',
    wilaya: 'Adrar',
    wilayaAr: 'أدرار',
    wilayaCode: '01',
    latitude: 27.8742,
    longitude: -0.2939,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'chlef-centre',
    name: 'Chlef',
    nameAr: 'الشلف',
    wilaya: 'Chlef',
    wilayaAr: 'الشلف',
    wilayaCode: '02',
    latitude: 36.165,
    longitude: 1.3345,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'laghouat',
    name: 'Laghouat',
    nameAr: 'الأغواط',
    wilaya: 'Laghouat',
    wilayaAr: 'الأغواط',
    wilayaCode: '03',
    latitude: 33.8,
    longitude: 2.865,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'oum-el-bouaghi',
    name: 'Oum El Bouaghi',
    nameAr: 'أم البواقي',
    wilaya: 'Oum El Bouaghi',
    wilayaAr: 'أم البواقي',
    wilayaCode: '04',
    latitude: 35.8775,
    longitude: 7.1135,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'batna',
    name: 'Batna',
    nameAr: 'باتنة',
    wilaya: 'Batna',
    wilayaAr: 'باتنة',
    wilayaCode: '05',
    latitude: 35.5559,
    longitude: 6.1741,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'biskra',
    name: 'Biskra',
    nameAr: 'بسكرة',
    wilaya: 'Biskra',
    wilayaAr: 'بسكرة',
    wilayaCode: '07',
    latitude: 34.85,
    longitude: 5.728,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'bechar',
    name: 'Béchar',
    nameAr: 'بشار',
    wilaya: 'Béchar',
    wilayaAr: 'بشار',
    wilayaCode: '08',
    latitude: 31.6167,
    longitude: -2.2167,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'bouira',
    name: 'Bouira',
    nameAr: 'البويرة',
    wilaya: 'Bouira',
    wilayaAr: 'البويرة',
    wilayaCode: '10',
    latitude: 36.3736,
    longitude: 3.902,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'tamanrasset',
    name: 'Tamanrasset',
    nameAr: 'تمنراست',
    wilaya: 'Tamanrasset',
    wilayaAr: 'تمنراست',
    wilayaCode: '11',
    latitude: 22.785,
    longitude: 5.5228,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'tebessa',
    name: 'Tébessa',
    nameAr: 'تبسة',
    wilaya: 'Tébessa',
    wilayaAr: 'تبسة',
    wilayaCode: '12',
    latitude: 35.4042,
    longitude: 8.1242,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'tlemcen',
    name: 'Tlemcen',
    nameAr: 'تلمسان',
    wilaya: 'Tlemcen',
    wilayaAr: 'تلمسان',
    wilayaCode: '13',
    latitude: 34.8828,
    longitude: -1.3167,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'tiaret',
    name: 'Tiaret',
    nameAr: 'تيارت',
    wilaya: 'Tiaret',
    wilayaAr: 'تيارت',
    wilayaCode: '14',
    latitude: 35.3711,
    longitude: 1.317,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'tizi-ouzou',
    name: 'Tizi Ouzou',
    nameAr: 'تيزي وزو',
    wilaya: 'Tizi Ouzou',
    wilayaAr: 'تيزي وزو',
    wilayaCode: '15',
    latitude: 36.7169,
    longitude: 4.0497,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'djelfa',
    name: 'Djelfa',
    nameAr: 'الجلفة',
    wilaya: 'Djelfa',
    wilayaAr: 'الجلفة',
    wilayaCode: '17',
    latitude: 34.6703,
    longitude: 3.263,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'jijel',
    name: 'Jijel',
    nameAr: 'جيجل',
    wilaya: 'Jijel',
    wilayaAr: 'جيجل',
    wilayaCode: '18',
    latitude: 36.819,
    longitude: 5.7667,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'setif',
    name: 'Sétif',
    nameAr: 'سطيف',
    wilaya: 'Sétif',
    wilayaAr: 'سطيف',
    wilayaCode: '19',
    latitude: 36.1919,
    longitude: 5.4136,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'saida',
    name: 'Saïda',
    nameAr: 'سعيدة',
    wilaya: 'Saïda',
    wilayaAr: 'سعيدة',
    wilayaCode: '20',
    latitude: 34.8303,
    longitude: 0.1517,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'skikda',
    name: 'Skikda',
    nameAr: 'سكيكدة',
    wilaya: 'Skikda',
    wilayaAr: 'سكيكدة',
    wilayaCode: '21',
    latitude: 36.876,
    longitude: 6.9094,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'sidi-bel-abbes',
    name: 'Sidi Bel Abbès',
    nameAr: 'سيدي بلعباس',
    wilaya: 'Sidi Bel Abbès',
    wilayaAr: 'سيدي بلعباس',
    wilayaCode: '22',
    latitude: 35.1878,
    longitude: -0.6308,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'annaba',
    name: 'Annaba',
    nameAr: 'عنابة',
    wilaya: 'Annaba',
    wilayaAr: 'عنابة',
    wilayaCode: '23',
    latitude: 36.9,
    longitude: 7.7667,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'guelma',
    name: 'Guelma',
    nameAr: 'قالمة',
    wilaya: 'Guelma',
    wilayaAr: 'قالمة',
    wilayaCode: '24',
    latitude: 36.4611,
    longitude: 7.4261,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'constantine',
    name: 'Constantine',
    nameAr: 'قسنطينة',
    wilaya: 'Constantine',
    wilayaAr: 'قسنطينة',
    wilayaCode: '25',
    latitude: 36.365,
    longitude: 6.6147,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'medea',
    name: 'Médéa',
    nameAr: 'المدية',
    wilaya: 'Médéa',
    wilayaAr: 'المدية',
    wilayaCode: '26',
    latitude: 36.2675,
    longitude: 2.7539,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'mostaganem',
    name: 'Mostaganem',
    nameAr: 'مستغانم',
    wilaya: 'Mostaganem',
    wilayaAr: 'مستغانم',
    wilayaCode: '27',
    latitude: 35.9311,
    longitude: 0.0892,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'msila',
    name: 'M’Sila',
    nameAr: 'المسيلة',
    wilaya: 'M’Sila',
    wilayaAr: 'المسيلة',
    wilayaCode: '28',
    latitude: 35.7058,
    longitude: 4.5419,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'mascara',
    name: 'Mascara',
    nameAr: 'معسكر',
    wilaya: 'Mascara',
    wilayaAr: 'معسكر',
    wilayaCode: '29',
    latitude: 35.3968,
    longitude: 0.14,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'ouargla',
    name: 'Ouargla',
    nameAr: 'ورقلة',
    wilaya: 'Ouargla',
    wilayaAr: 'ورقلة',
    wilayaCode: '30',
    latitude: 31.9494,
    longitude: 5.3253,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'oran',
    name: 'Oran',
    nameAr: 'وهران',
    wilaya: 'Oran',
    wilayaAr: 'وهران',
    wilayaCode: '31',
    latitude: 35.6971,
    longitude: -0.6308,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'el-bayadh',
    name: 'El Bayadh',
    nameAr: 'البيض',
    wilaya: 'El Bayadh',
    wilayaAr: 'البيض',
    wilayaCode: '32',
    latitude: 33.68,
    longitude: 1.0192,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'illizi',
    name: 'Illizi',
    nameAr: 'إليزي',
    wilaya: 'Illizi',
    wilayaAr: 'إليزي',
    wilayaCode: '33',
    latitude: 26.4833,
    longitude: 8.4667,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'bordj-bou-arreridj',
    name: 'Bordj Bou Arréridj',
    nameAr: 'برج بوعريريج',
    wilaya: 'Bordj Bou Arréridj',
    wilayaAr: 'برج بوعريريج',
    wilayaCode: '34',
    latitude: 36.0731,
    longitude: 4.7608,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'el-tarf',
    name: 'El Tarf',
    nameAr: 'الطارف',
    wilaya: 'El Tarf',
    wilayaAr: 'الطارف',
    wilayaCode: '36',
    latitude: 36.7672,
    longitude: 8.3136,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'tindouf',
    name: 'Tindouf',
    nameAr: 'تندوف',
    wilaya: 'Tindouf',
    wilayaAr: 'تندوف',
    wilayaCode: '37',
    latitude: 27.6753,
    longitude: -8.1475,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'tissemsilt',
    name: 'Tissemsilt',
    nameAr: 'تيسمسيلت',
    wilaya: 'Tissemsilt',
    wilayaAr: 'تيسمسيلت',
    wilayaCode: '38',
    latitude: 35.6072,
    longitude: 1.8106,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'el-oued',
    name: 'El Oued',
    nameAr: 'الوادي',
    wilaya: 'El Oued',
    wilayaAr: 'الوادي',
    wilayaCode: '39',
    latitude: 33.3683,
    longitude: 6.8675,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'khenchela',
    name: 'Khenchela',
    nameAr: 'خنشلة',
    wilaya: 'Khenchela',
    wilayaAr: 'خنشلة',
    wilayaCode: '40',
    latitude: 35.4358,
    longitude: 7.1433,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'souk-ahras',
    name: 'Souk Ahras',
    nameAr: 'سوق أهراس',
    wilaya: 'Souk Ahras',
    wilayaAr: 'سوق أهراس',
    wilayaCode: '41',
    latitude: 36.2864,
    longitude: 7.9511,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'tipaza',
    name: 'Tipaza',
    nameAr: 'تيبازة',
    wilaya: 'Tipaza',
    wilayaAr: 'تيبازة',
    wilayaCode: '42',
    latitude: 36.5892,
    longitude: 2.4486,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'mila',
    name: 'Mila',
    nameAr: 'ميلة',
    wilaya: 'Mila',
    wilayaAr: 'ميلة',
    wilayaCode: '43',
    latitude: 36.4503,
    longitude: 6.2644,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'ain-defla',
    name: 'Aïn Defla',
    nameAr: 'عين الدفلى',
    wilaya: 'Aïn Defla',
    wilayaAr: 'عين الدفلى',
    wilayaCode: '44',
    latitude: 36.2639,
    longitude: 1.9678,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'naama',
    name: 'Naâma',
    nameAr: 'النعامة',
    wilaya: 'Naâma',
    wilayaAr: 'النعامة',
    wilayaCode: '45',
    latitude: 33.2667,
    longitude: -0.3,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'ain-temouchent',
    name: 'Aïn Témouchent',
    nameAr: 'عين تموشنت',
    wilaya: 'Aïn Témouchent',
    wilayaAr: 'عين تموشنت',
    wilayaCode: '46',
    latitude: 35.2978,
    longitude: -1.14,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'ghardaia',
    name: 'Ghardaïa',
    nameAr: 'غرداية',
    wilaya: 'Ghardaïa',
    wilayaAr: 'غرداية',
    wilayaCode: '47',
    latitude: 32.49,
    longitude: 3.6733,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'relizane',
    name: 'Relizane',
    nameAr: 'غليزان',
    wilaya: 'Relizane',
    wilayaAr: 'غليزان',
    wilayaCode: '48',
    latitude: 35.7372,
    longitude: 0.5556,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'timimoun',
    name: 'Timimoun',
    nameAr: 'تيميمون',
    wilaya: 'Timimoun',
    wilayaAr: 'تيميمون',
    wilayaCode: '49',
    latitude: 29.2639,
    longitude: 0.2306,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'bordj-badji-mokhtar',
    name: 'Bordj Badji Mokhtar',
    nameAr: 'برج باجي مختار',
    wilaya: 'Bordj Badji Mokhtar',
    wilayaAr: 'برج باجي مختار',
    wilayaCode: '50',
    latitude: 21.3256,
    longitude: 0.9556,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'ouled-djellal',
    name: 'Ouled Djellal',
    nameAr: 'أولاد جلال',
    wilaya: 'Ouled Djellal',
    wilayaAr: 'أولاد جلال',
    wilayaCode: '51',
    latitude: 34.4269,
    longitude: 5.0722,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'beni-abbes',
    name: 'Béni Abbès',
    nameAr: 'بني عباس',
    wilaya: 'Béni Abbès',
    wilayaAr: 'بني عباس',
    wilayaCode: '52',
    latitude: 30.13,
    longitude: -2.17,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'in-salah',
    name: 'In Salah',
    nameAr: 'عين صالح',
    wilaya: 'In Salah',
    wilayaAr: 'عين صالح',
    wilayaCode: '53',
    latitude: 27.1936,
    longitude: 2.4608,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'in-guezzam',
    name: 'In Guezzam',
    nameAr: 'عين قزام',
    wilaya: 'In Guezzam',
    wilayaAr: 'عين قزام',
    wilayaCode: '54',
    latitude: 19.5686,
    longitude: 5.7722,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'touggourt',
    name: 'Touggourt',
    nameAr: 'تقرت',
    wilaya: 'Touggourt',
    wilayaAr: 'تڨرت',
    wilayaCode: '55',
    latitude: 33.1,
    longitude: 6.0667,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'djanet',
    name: 'Djanet',
    nameAr: 'جانت',
    wilaya: 'Djanet',
    wilayaAr: 'جانت',
    wilayaCode: '56',
    latitude: 24.5542,
    longitude: 9.4843,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'el-mghair',
    name: 'El M’Ghair',
    nameAr: 'المغير',
    wilaya: 'El M’Ghair',
    wilayaAr: 'المغير',
    wilayaCode: '57',
    latitude: 33.9539,
    longitude: 5.9247,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
  {
    id: 'el-meniaa',
    name: 'El Meniaa',
    nameAr: 'المنيعة',
    wilaya: 'El Meniaa',
    wilayaAr: 'المنيعة',
    wilayaCode: '58',
    latitude: 30.5833,
    longitude: 2.8833,
    radiusMeters: 8000,
    verifiedNeighbors: 0,
  },
];

export function findNeighborhood(id: string): Neighborhood | undefined {
  return NEIGHBORHOODS.find((n) => n.id === id);
}

/**
 * Quartiers dont le fil est partagé avec celui-ci : le quartier lui-même, son
 * quartier de rattachement s'il est jumelé, et les quartiers rattachés à lui.
 * L'origine exacte reste affichée sur chaque publication (§2).
 */
export function sharedFeedNeighborhoodIds(id: string): string[] {
  const neighborhood = findNeighborhood(id);
  if (!neighborhood) return [id];

  const root = neighborhood.twinnedWith ?? neighborhood.id;
  const ids = new Set<string>([neighborhood.id, root]);
  for (const other of NEIGHBORHOODS) {
    if (other.twinnedWith === root) ids.add(other.id);
  }
  return [...ids];
}
